version: "3.3"

services:
  web:
    container_name: web
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  worker: 
    build: .
    command: celery -A main.celery worker --loglevel=info
    depends_on:
      - redis
      - web